wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
learning_rate:
  value: 0.04341301751073554
loss:
  value: cross_entropy
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: xavier
