wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
learning_rate:
  value: 0.00567115523504433
loss:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_decay:
  value: 0.005
weight_init:
  value: xavier
