wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
learning_rate:
  value: 0.04125813080286185
loss:
  value: cross_entropy
optimizer:
  value: momentum
weight_decay:
  value: 0.005
weight_init:
  value: random
