wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
learning_rate:
  value: 0.02322453081062665
loss:
  value: cross_entropy
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: zeros
