wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
learning_rate:
  value: 0.02754658401032604
loss:
  value: cross_entropy
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: zeros
