wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
learning_rate:
  value: 0.03208796140471683
loss:
  value: cross_entropy
optimizer:
  value: sgd
weight_decay:
  value: 0.005
weight_init:
  value: zeros
