wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
learning_rate:
  value: 0.0041988081872753776
loss:
  value: mse
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: zeros
