wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
learning_rate:
  value: 0.008526366433712832
loss:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: zeros
