_wandb:
    value:
        cli_version: 0.25.0
        e:
            0w1hovvdwyud2t6295jfzmm6pwnd9ja1:
                codePath: question_2_point_2.py
                codePathLocal: question_2_point_2.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "789284122624"
                        used: "508190793728"
                email: varuna433@gmail.com
                executable: C:\Users\gurra\anaconda3\envs\DA_Ass1\python.exe
                git:
                    commit: 0123f066251c3011fe6a21833d1a1c51f2976e50
                    remote: https://github.com/Eswar-gupta/da6401_assignment_1.git
                host: DESKTOP-LO1APP7
                memory:
                    total: "16849293312"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\gurra\OneDrive\Desktop\1Acads\sem-6\DA6401-DL\Final_DL_Ass1\da6401_assignment_1\question_2_point_2.py
                python: CPython 3.11.0
                root: C:\Users\gurra\OneDrive\Desktop\1Acads\sem-6\DA6401-DL\Final_DL_Ass1\da6401_assignment_1
                startedAt: "2026-03-07T16:34:52.067001Z"
                writerId: 0w1hovvdwyud2t6295jfzmm6pwnd9ja1
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 3
                - 8
                - 14
                - 62
            "4": 3.11.0
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 17
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
learning_rate:
    value: 0.04451524045172224
loss:
    value: mse
optimizer:
    value: momentum
weight_decay:
    value: 0.0005
weight_init:
    value: random
